{
  description = "Mind-the-Gap tools and live image";

  inputs = {
    # Pinned, as current unstable iso with grub does not boot
    nixpkgs.url = "github:NixOS/nixpkgs/release-25.11";

    # Pinned nixpkgs rust is to currently to old
    fenix.url = "github:nix-community/fenix";
    fenix.inputs.nixpkgs.follows = "nixpkgs";

    # Cargo nix integration
    naersk.url = "github:nix-community/naersk";
    naersk.inputs.nixpkgs.follows = "nixpkgs";
    naersk.inputs.fenix.follows = "fenix";
  };

  outputs = { self, nixpkgs, fenix, naersk }:
    let
      # List of all supported system architectures
      allSystems = [ "x86_64-linux" "aarch64-linux" ];

      # Helper to generate attrset entry for each system
      forEachSystem = nixpkgs.lib.genAttrs allSystems;

      # Helper to generate nameable attrset entry for each system
      forEachSystem' = f: builtins.listToAttrs (map f allSystems);

      # Provide newer version of rust
      mkToolchain = system: fenix.packages.${system}.stable;

      # Provide naersk with newer version of rust
      mkNaersk = system: naersk.lib.${system}.override {
        inherit (mkToolchain system) cargo rustc;
      };
    in
    {
      # nixos-test to validate live system environment
      checks = forEachSystem (system: {
        live-system =
          let
            pkgs = nixpkgs.legacyPackages.${system};
            nixos-lib = import (pkgs.path + "/nixos/lib") { };
          in
          (nixos-lib.runTest {
            hostPkgs = pkgs;

            # Make self available in the node config
            node.specialArgs = { inherit self; };

            # Add nixos test module
            imports = [ ./nixos-test.nix ];
          }).config.result;
      });

      # Shell used for development
      devShells = forEachSystem (system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          toolchain = mkToolchain system;
        in
        {
          default = pkgs.mkShell {
            nativeBuildInputs =
              (with pkgs; [ pkg-config rustPlatform.bindgenHook sequoia-sq gnupg ])
                ++ (with toolchain; [ cargo rustc rust-analyzer rustfmt ]);

            buildInputs = with pkgs; [ gmp nettle pcsclite ];

            # Provide rust-src to language server
            RUST_SRC_PATH = "${toolchain.rust-src}/lib/rustlib/src/rust/library";

            # Expose shared libraries so `cargo test` can load them at runtime
            shellHook = with pkgs; ''
              export LD_LIBRARY_PATH=${lib.makeLibraryPath [ gmp nettle pcsclite ]}:$LD_LIBRARY_PATH
            '';
          };
        }
      );

      # Bootable iso with live system to run on air-gapped device
      nixosConfigurations = forEachSystem' (system: {
        name = "live-${system}";
        value = nixpkgs.lib.nixosSystem {
          inherit system;
          modules = [
            # Add mind-the-gap through a nixpkgs overlay
            { nixpkgs.overlays = [ self.overlays.default ]; }
            # Add live system config module
            (import ./live-system.nix)
          ];
        };
      });

      # Simple overlay to provide command line derivation
      overlays.default = final: prev: {
        inherit (self.packages.${prev.stdenv.hostPlatform.system}) mind-the-gap;
      };

      # Buildable outputs are:
      packages = forEachSystem (system: {
        # - Provide command line interface as default package
        default = self.packages.${system}.mind-the-gap;

        # - Provide live iso image as derivation
        iso = self.nixosConfigurations."live-${system}".config.system.build.isoImage;

        # - Build the command line interface with naersk
        mind-the-gap = (mkNaersk system).buildPackage (
          let
            pkgs = nixpkgs.legacyPackages.${system};
            libPath = with pkgs; lib.makeLibraryPath [ gmp nettle pcsclite ];
          in
          {
            src = ./.;

            nativeBuildInputs = with pkgs; [
              makeWrapper
              pkg-config
              rustPlatform.bindgenHook
            ];

            buildInputs = with pkgs; [ gmp nettle pcsclite ];

            # Run tests with needed command line tools
            doCheck = true;

            checkInputs = with pkgs; [ sequoia-sq gnupg ];

            # Expose shared libraries so `cargo test` can load them at runtime
            LD_LIBRARY_PATH = libPath;

            # GnuPG can not be run without access to its home dir
            GNUPGHOME = "/tmp";

            postInstall = ''
              # Man pages and completion support are generated by additional binary
              $out/bin/mind-the-build $out
              rm $out/bin/mind-the-build

              # Ensure needed dependencies can be located
              wrapProgram "$out/bin/mind-the-gap" --prefix LD_LIBRARY_PATH : "${libPath}"
            '';
          }
        );
      });
    };
}
